name: list_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  dio: ^5.9.1
  build_runner: ^2.11.1
  provider: ^6.1.5+1
  flutter_riverpod: 2.6.1
  json_serializable: 6.11.2
  flutter_secure_storage: ^10.0.0
  flutter_slidable: ^4.0.3
  http: ^1.6.0


flutter:
  uses-material-design: true
